<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ListPelabuhan extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $codes = array(
			array('code' => 'IDADB', 'name' => 'Adang Bay'),			
            array('code' => 'IDAEG', 'name' => 'Aekgodang'),			
            array('code' => 'IDAKE', 'name' => 'Akeselaka'),			
            array('code' => 'IDARD', 'name' => 'Alor Island'),			
            array('code' => 'IDAHI', 'name' => 'Amahai'),			
            array('code' => 'IDAMA', 'name' => 'Amamapare, Ij'),			
            array('code' => 'IDAMQ', 'name' => 'Ambon, Molucas'),			
            array('code' => 'IDAPN', 'name' => 'Ampana'),			
            array('code' => 'IDAMP', 'name' => 'Ampenan, Bali'),			
            array('code' => 'IDANG', 'name' => 'Angar'),			
            array('code' => 'IDAGD', 'name' => 'Anggi'),			
            array('code' => 'IDANR', 'name' => 'Anyer Kidul'),			
            array('code' => 'IDAAS', 'name' => 'Apalapsili'),			
            array('code' => 'IDAPI', 'name' => 'Api Api'),			
            array('code' => 'IDAJN', 'name' => 'Arjuna, Java'),			
            array('code' => 'IDARB', 'name' => 'Aroe Bay'),			
            array('code' => 'IDARJ', 'name' => 'Arso'),			
            array('code' => 'IDAUN', 'name' => 'Arun'),			
            array('code' => 'IDIAM', 'name' => 'Asam Asam'),			
            array('code' => 'IDASI', 'name' => 'Asike'),			
            array('code' => 'IDABU', 'name' => 'Atambua'),			
            array('code' => 'IDAUT', 'name' => 'Atauro'),			
            array('code' => 'IDAYW', 'name' => 'Ayawasi'),			
            array('code' => 'IDBXD', 'name' => 'Bade'),			
            array('code' => 'IDBJW', 'name' => 'Bajawa'),			
            array('code' => 'IDBPN', 'name' => 'Balikpapan, Kalimantan'),			
            array('code' => 'IDBAL', 'name' => 'Balongan Terminal'),			
            array('code' => 'IDNAF', 'name' => 'Banaina'),			
            array('code' => 'IDBTJ', 'name' => 'Banda Aceh'),			
            array('code' => 'IDNDA', 'name' => 'Bandanaira'),			
            array('code' => 'IDTKG', 'name' => 'Bandar Lampung'),			
            array('code' => 'IDBDO', 'name' => 'Bandung, Java'),			
            array('code' => 'IDBGG', 'name' => 'Banggai'),			
            array('code' => 'IDBDJ', 'name' => 'Banjarmasin'),			
            array('code' => 'IDBJU', 'name' => 'Banjuwangi, Java'),			
            array('code' => 'IDBTN', 'name' => 'Banten'),			
            array('code' => 'IDIBL', 'name' => 'Bantul'),			
            array('code' => 'IDBTH', 'name' => 'Batam (ex Batu Besar)'),			
            array('code' => 'IDBTM', 'name' => 'Batam Island'),			
            array('code' => 'IDBUR', 'name' => 'Batu Ampal'),			
            array('code' => 'IDBAK', 'name' => 'Batu Kilat'),			
            array('code' => 'IDBTW', 'name' => 'Batulicin'),			
            array('code' => 'IDBUW', 'name' => 'Baubau, Butung'),			
            array('code' => 'IDBCH', 'name' => 'Baucau'),			
            array('code' => 'IDBEK', 'name' => 'Bekapai Terminal'),			
            array('code' => 'IDBKA', 'name' => 'Bekasi'),			
            array('code' => 'IDBNT', 'name' => 'Belanak Terminal'),			
            array('code' => 'IDBLW', 'name' => 'Belawan, Sumatra'),			
            array('code' => 'IDBET', 'name' => 'Belida Terminal'),			
            array('code' => 'IDBLV', 'name' => 'Beliling'),			
            array('code' => 'IDBLT', 'name' => 'Belitung'),			
            array('code' => 'IDBEN', 'name' => 'Benete'),			
            array('code' => 'IDBKI', 'name' => 'Bengkalis, St'),			
            array('code' => 'IDBKS', 'name' => 'Bengkulu, Sumatra'),			
            array('code' => 'IDBOA', 'name' => 'Benoa, Bali'),			
            array('code' => 'IDBEJ', 'name' => 'Berau'),			
            array('code' => 'IDBIK', 'name' => 'Biak, Irian Jaya'),			
            array('code' => 'IDBMT', 'name' => 'Bima Terminal, Jv'),			
            array('code' => 'IDBMU', 'name' => 'Bima, Sb'),			
            array('code' => 'IDNTI', 'name' => 'Bintuni'),			
            array('code' => 'IDBIR', 'name' => 'Biringkassi'),			
            array('code' => 'IDBIT', 'name' => 'Bitung, Sulawesi'),			
            array('code' => 'IDBLL', 'name' => 'Blang Lancang, St'),			
            array('code' => 'IDBLI', 'name' => 'Blinju, Banka'),			
            array('code' => 'IDBOG', 'name' => 'Bogor'),			
            array('code' => 'IDBUI', 'name' => 'Bokondini'),			
            array('code' => 'IDBJG', 'name' => 'Bolaang'),			
            array('code' => 'IDBNG', 'name' => 'Bonggala'),			
            array('code' => 'IDBXT', 'name' => 'Bontang, Kl'),			
            array('code' => 'IDBUN', 'name' => 'Buatan'),			
            array('code' => 'IDBUA', 'name' => 'Bula'),			
            array('code' => 'IDBUG', 'name' => 'Buleleng, Bali'),			
            array('code' => 'IDBYQ', 'name' => 'Bunyu'),			
            array('code' => 'IDUOL', 'name' => 'Buol'),			
            array('code' => 'IDCSA', 'name' => 'Cape Sago'),			
            array('code' => 'IDCEB', 'name' => 'Celukan Bawang, Bl'),			
            array('code' => 'IDCEN', 'name' => 'Cengkareng'),			
            array('code' => 'IDICU', 'name' => 'Cepu'),			
            array('code' => 'IDCER', 'name' => 'Cereweh'),			
            array('code' => 'IDCIG', 'name' => 'Cigading'),			
            array('code' => 'IDCIK', 'name' => 'Cikampek'),			
            array('code' => 'IDCXP', 'name' => 'Cilacap (Tjilatjap)'),			
            array('code' => 'IDCDK', 'name' => 'Cilandak'),			
            array('code' => 'IDCIN', 'name' => 'Cinta, Java'),			
            array('code' => 'IDCTT', 'name' => 'Ciputat'),			
            array('code' => 'IDCBN', 'name' => 'Cirebon (Tjeribon)'),			
            array('code' => 'IDCIW', 'name' => 'Ciwandan'),			
            array('code' => 'IDDAS', 'name' => 'Dabo, Singkep Isl'),			
            array('code' => 'IDDMA', 'name' => 'Demta'),			
            array('code' => 'IDDPS', 'name' => 'Denpasar, Bali'),			
            array('code' => 'IDDIV', 'name' => 'Diviematra'),			
            array('code' => 'IDDJA', 'name' => 'Djankar'),			
            array('code' => 'IDDOB', 'name' => 'Dobo'),			
            array('code' => 'IDDOG', 'name' => 'Donggi'),			
            array('code' => 'IDDUM', 'name' => 'Dumai, Sumatra'),			
            array('code' => 'IDELA', 'name' => 'Elat'),			
            array('code' => 'IDEWI', 'name' => 'Enarotali'),			
            array('code' => 'IDENE', 'name' => 'Ende, Flores'),			
            array('code' => 'IDEWE', 'name' => 'Ewer'),			
            array('code' => 'IDFKQ', 'name' => 'Fak Fak, Irian Jaya'),			
            array('code' => 'IDGAG', 'name' => 'Gag Island'),			
            array('code' => 'IDGLX', 'name' => 'Galela, Halmahera'),			
            array('code' => 'IDGEB', 'name' => 'Gebe'),			
            array('code' => 'IDGEE', 'name' => 'Gee I.'),			
            array('code' => 'IDIGR', 'name' => 'Gianyar'),			
            array('code' => 'IDGIL', 'name' => 'Gilimanuk, Bali'),			
            array('code' => 'IDGTO', 'name' => 'Gorontalo, Sulawesi'),			
            array('code' => 'IDGRE', 'name' => 'Gresik, Java'),			
            array('code' => 'IDGNS', 'name' => 'Gunung Sitoli, St'),			
            array('code' => 'IDILA', 'name' => 'Illaga'),			
            array('code' => 'IDINA', 'name' => 'Inanwatan'),			
            array('code' => 'IDIBT', 'name' => 'Indonesia Bulk Terminal'),			
            array('code' => 'IDJBT', 'name' => 'Jabung Terminal'),			
            array('code' => 'IDUTC', 'name' => 'Jakarta UTC1'),			
            array('code' => 'IDUTE', 'name' => 'Jakarta UTC3'),			
            array('code' => 'IDJKT', 'name' => 'Jakarta, Java'),			
            array('code' => 'IDDJB', 'name' => 'Jambi, Sumatra'),			
            array('code' => 'IDJBG', 'name' => 'Jatibarang'),			
            array('code' => 'IDJTH', 'name' => 'Jatitujuh'),			
            array('code' => 'IDDJJ', 'name' => 'Jayapura, Irian Jaya'),			
            array('code' => 'IDJEM', 'name' => 'Jember'),			
            array('code' => 'IDJEP', 'name' => 'Jepara'),			
            array('code' => 'IDKAB', 'name' => 'Kabil'),			
            array('code' => 'IDKAH', 'name' => 'Kahayan Bay'),			
            array('code' => 'IDKHY', 'name' => 'Kahyangan'),			
            array('code' => 'IDKNG', 'name' => 'Kaimana, Irian Jaya'),			
            array('code' => 'IDKJN', 'name' => 'Kajang'),			
            array('code' => 'IDKBH', 'name' => 'Kalabahi'),			
            array('code' => 'IDKSO', 'name' => 'Kalbut Situbondo'),			
            array('code' => 'IDKAT', 'name' => 'Kalianget'),			
            array('code' => 'IDKLT', 'name' => 'Kaltim'),			
            array('code' => 'IDKAM', 'name' => 'Kambunong, Celebes'),			
            array('code' => 'IDKRG', 'name' => 'Kariangau'),			
            array('code' => 'IDOKA', 'name' => 'Karimun Besar Offshore'),			
            array('code' => 'IDKAR', 'name' => 'Karosa, Sulawesi'),			
            array('code' => 'IDKBF', 'name' => 'Karubaga'),			
            array('code' => 'IDKAS', 'name' => 'Kasim, Ij'),			
            array('code' => 'IDKSE', 'name' => 'Kassue'),			
            array('code' => 'IDKAU', 'name' => 'Kau'),			
            array('code' => 'IDKEQ', 'name' => 'Kebar'),			
            array('code' => 'IDKEA', 'name' => 'Keisah'),			
            array('code' => 'IDLLN', 'name' => 'Kelila'),			
            array('code' => 'IDKLQ', 'name' => 'Keluang'),			
            array('code' => 'IDKEM', 'name' => 'Kempo, Sb'),			
            array('code' => 'IDKDI', 'name' => 'Kendari, Sulawesi'),			
            array('code' => 'IDKDW', 'name' => 'Kendawangan'),			
            array('code' => 'IDKEI', 'name' => 'Kepi'),			
            array('code' => 'IDKRC', 'name' => 'Kerinci'),			
            array('code' => 'IDKTG', 'name' => 'Ketapang, Kl'),			
            array('code' => 'IDKID', 'name' => 'Kidjang, Bintan'),			
            array('code' => 'IDKIJ', 'name' => 'Kijang'),			
            array('code' => 'IDKMM', 'name' => 'Kimam'),			
            array('code' => 'IDKOJ', 'name' => 'Koja'),			
            array('code' => 'IDKOK', 'name' => 'Kokas'),			
            array('code' => 'IDKOX', 'name' => 'Kokonao'),			
            array('code' => 'IDKOL', 'name' => 'Kolaka'),			
            array('code' => 'IDKNL', 'name' => 'Kolonodale'),			
            array('code' => 'IDKCI', 'name' => 'Kon'),			
            array('code' => 'IDKOD', 'name' => 'Kotabangun'),			
            array('code' => 'IDKBU', 'name' => 'Kotabaru'),			
            array('code' => 'IDKPN', 'name' => 'Kotapinang, Baru'),			
            array('code' => 'IDENO', 'name' => 'Kuala Enok'),			
            array('code' => 'IDKKA', 'name' => 'Kuala Kapuas, Kl'),			
            array('code' => 'IDKMA', 'name' => 'Kuala Mandah, Sumatra'),			
            array('code' => 'IDKUA', 'name' => 'Kualalangsa'),			
            array('code' => 'IDKTJ', 'name' => 'Kualatanjung'),			
            array('code' => 'IDKTK', 'name' => 'Kualatungkal'),			
            array('code' => 'IDKUM', 'name' => 'Kumai'),			
            array('code' => 'IDKKB', 'name' => 'Kunak, Borneo'),			
            array('code' => 'IDKOE', 'name' => 'Kupang, Timor'),			
            array('code' => 'IDLBJ', 'name' => 'Labuanbajo'),
            
            array('code' => 'IDLAH', 'name' => 'Labuha, Molucas'),
            array('code' => 'IDLAJ', 'name' => 'Labuhan'),
            array('code' => 'IDLAT', 'name' => 'Lalang Terminal, St'),
            array('code' => 'IDLUV', 'name' => 'Langgur'),
            array('code' => 'IDLAS', 'name' => 'Langsa, Sumatra'),
            array('code' => 'IDLKA', 'name' => 'Larantuka'),
            array('code' => 'IDLRT', 'name' => 'Larat'),
            array('code' => 'IDLLA', 'name' => 'Lawe-Lawe, Kl'),
            array('code' => 'IDLHI', 'name' => 'Lereh'),
            array('code' => 'IDLWE', 'name' => 'Lewoleba'),
            array('code' => 'IDLSX', 'name' => 'Lhok Sukon'),
            array('code' => 'IDLHK', 'name' => 'Lhoknga'),
            array('code' => 'IDLSW', 'name' => 'Lhokseumawe'),
            array('code' => 'IDLIF', 'name' => 'Lifamatola'),
            array('code' => 'IDLBM', 'name' => 'Lobam'),
            array('code' => 'IDLKI', 'name' => 'Loki'),
            array('code' => 'IDLOL', 'name' => 'Loli'),
            array('code' => 'IDLOM', 'name' => 'Lombok'),
            array('code' => 'IDLMB', 'name' => 'Lombok Strait'),
            array('code' => 'IDLPU', 'name' => 'Long Apung'),
            array('code' => 'IDLBW', 'name' => 'Long Bawan'),
            array('code' => 'IDLYK', 'name' => 'Lunyuk'),
            array('code' => 'IDLUW', 'name' => 'Luwuk'),
            array('code' => 'IDMDR', 'name' => 'Madura Terminal'),
            array('code' => 'IDMAJ', 'name' => 'Majene, Sv'),
            array('code' => 'IDMAK', 'name' => 'Makassar'),
            array('code' => 'IDMLG', 'name' => 'Malang'),
            array('code' => 'IDMPT', 'name' => 'Maliana'),
            array('code' => 'IDMLI', 'name' => 'Malili, Sulawesi'),
            array('code' => 'IDMJU', 'name' => 'Mamuju'),
            array('code' => 'IDMDC', 'name' => 'Manado'),
            array('code' => 'IDMAN', 'name' => 'Manggar'),
            array('code' => 'IDMGB', 'name' => 'Manggis'),
            array('code' => 'IDMKJ', 'name' => 'Mangkajang'),
            array('code' => 'IDMAL', 'name' => 'Mangole'),
            array('code' => 'IDMJY', 'name' => 'Mangunjaya'),
            array('code' => 'IDMKW', 'name' => 'Manokwari, Irian Jaya'),
            array('code' => 'IDMNT', 'name' => 'Mantang, Riau'),
            array('code' => 'IDMAI', 'name' => 'Mapia I.s'),
            array('code' => 'IDMAR', 'name' => 'Marabahan'),
            array('code' => 'IDMSI', 'name' => 'Masalembo'),
            array('code' => 'IDMXB', 'name' => 'Masamba'),
            array('code' => 'IDMWK', 'name' => 'Matak'),
            array('code' => 'IDAMI', 'name' => 'Mataram'),
            array('code' => 'IDMOF', 'name' => 'Maumere, Flores'),
            array('code' => 'IDMES', 'name' => 'Medan, Sumatra'),
            array('code' => 'IDMNA', 'name' => 'Melonguanne'),
            array('code' => 'IDMRK', 'name' => 'Merak, Java'),
            array('code' => 'IDMRB', 'name' => 'Merantibunting, Sumatra'),
            array('code' => 'IDMKQ', 'name' => 'Merauke, Irian Jaya'),
            array('code' => 'IDRDE', 'name' => 'Merdey'),
            array('code' => 'IDMEQ', 'name' => 'Meulaboh, Sumatra'),
            array('code' => 'IDMDP', 'name' => 'Mindiptana'),
            array('code' => 'IDMIT', 'name' => 'Misool Terminal'),
            array('code' => 'IDONI', 'name' => 'Moanamani'),
            array('code' => 'IDMOR', 'name' => 'Mornopo'),
            array('code' => 'IDOZI', 'name' => 'Morotai I'),
            array('code' => 'IDMBK', 'name' => 'Muara Bangkong'),
            array('code' => 'IDMUB', 'name' => 'Muara Berau'),
            array('code' => 'IDMUD', 'name' => 'Muara Djawa'),
            array('code' => 'IDMUP', 'name' => 'Muara Pegah'),
            array('code' => 'IDMSB', 'name' => 'Muara Siberut'),
            array('code' => 'IDMPC', 'name' => 'Muko-Muko'),
            array('code' => 'IDLII', 'name' => 'Mulia'),
            array('code' => 'IDMUO', 'name' => 'Muntok, Banka'),
            array('code' => 'IDMRI', 'name' => 'Musi River, Sumatra'),
            array('code' => 'IDMUF', 'name' => 'Muting'),
            array('code' => 'IDMTU', 'name' => 'Muturi'),
            array('code' => 'IDNBX', 'name' => 'Nabire'),
            array('code' => 'IDNAH', 'name' => 'Naha'),
            array('code' => 'IDNAM', 'name' => 'Namlea'),
            array('code' => 'IDNRE', 'name' => 'Namrole'),
            array('code' => 'IDNPO', 'name' => 'Nangapinoh'),
            array('code' => 'IDNTX', 'name' => 'Natuna Ranai'),
            array('code' => 'IDNPL', 'name' => 'North Pulau Laut'),
            array('code' => 'IDFOO', 'name' => 'Numfoor'),
            array('code' => 'IDNNX', 'name' => 'Nunukan'),
            array('code' => 'IDOBD', 'name' => 'Obano'),
            array('code' => 'IDOBI', 'name' => 'Obi Island'),
            array('code' => 'IDOEC', 'name' => 'Ocussi'),
            array('code' => 'IDOKQ', 'name' => 'Okaba, Irian Jaya'),
            array('code' => 'IDOKL', 'name' => 'Oksibil'),
            array('code' => 'IDOJA', 'name' => 'Olah Jasa Andal/Jakarta'),
            array('code' => 'IDOLO', 'name' => 'Olee Lheue'),
            array('code' => 'IDORA', 'name' => 'Oransbari'),
            array('code' => 'IDPDG', 'name' => 'Padang'),
            array('code' => 'IDPAG', 'name' => 'Pagatan, Kalimantan'),
            array('code' => 'IDPGA', 'name' => 'Pagerungan'),
            array('code' => 'IDPGM', 'name' => 'Pagimana'),
            array('code' => 'IDPAI', 'name' => 'Paiton'),
            array('code' => 'IDPKY', 'name' => 'Palangkaraya'),
            array('code' => 'IDPPO', 'name' => 'Palapo, Sulawesi'),
            array('code' => 'IDPLM', 'name' => 'Palembang, Sumatra'),
            array('code' => 'IDPBW', 'name' => 'Palibelo'),
            array('code' => 'IDPAL', 'name' => 'Palu'),
            array('code' => 'IDPNN', 'name' => 'Pamanukan, Java'),
            array('code' => 'IDPRN', 'name' => 'Panarukan, Java'),
            array('code' => 'IDPJM', 'name' => 'Pandjung Mani'),
            array('code' => 'IDPGX', 'name' => 'Pangkal Balam, Banka'),
            array('code' => 'IDPKR', 'name' => 'Pangkalan Brandan, Sumatra'),
            array('code' => 'IDPKS', 'name' => 'Pangkalan Susu, Sumatra'),
            array('code' => 'IDPKN', 'name' => 'Pangkalanbuun'),
            array('code' => 'IDPGK', 'name' => 'Pangkalpinang, Banka'),
            array('code' => 'IDPNJ', 'name' => 'Panjang'),
            array('code' => 'IDPJG', 'name' => 'Panjang (Lampung, Sumatra)'),
            array('code' => 'IDPTL', 'name' => 'Pantoloan, Sv'),
            array('code' => 'IDPAP', 'name' => 'Pare Pare'),
            array('code' => 'IDPPR', 'name' => 'Pasir Pangarayan'),
            array('code' => 'IDPAS', 'name' => 'Pasir Panjang'),
            array('code' => 'IDPAZ', 'name' => 'Pasuruan, Java'),
            array('code' => 'IDPEX', 'name' => 'Pekalongan, Java'),
            array('code' => 'IDPKU', 'name' => 'Pekanbaru, Sumatra'),
            array('code' => 'IDFTG', 'name' => 'Pelabuhan Futong Terminal'),
            array('code' => 'IDPEM', 'name' => 'Pemangkat, Kl'),

            array('code' => 'IDPDO', 'name' => 'Pendopo'),
            array('code' => 'IDPNG', 'name' => 'Penuba'),
            array('code' => 'IDPER', 'name' => 'Perawang'),
            array('code' => 'IDPWG', 'name' => 'Perawang, Sumatra'),
            array('code' => 'IDPBG', 'name' => 'Perbaungan'),
            array('code' => 'IDPIR', 'name' => 'Piru'),
            array('code' => 'IDPLA', 'name' => 'Plaju, Sumatra'),
            array('code' => 'IDPMK', 'name' => 'Pomako'),
            array('code' => 'IDPUM', 'name' => 'Pomalaa, Sulawesi'),
            array('code' => 'IDPCB', 'name' => 'Pondok Cabe'),
            array('code' => 'IDPNK', 'name' => 'Pontianak, Kalimantan'),
            array('code' => 'IDPMG', 'name' => 'Port Meneng'),
            array('code' => 'IDPTO', 'name' => 'Port Okha'),
            array('code' => 'IDSGO', 'name' => 'Port Segoro Fajar Satryo/Jakarta'),
            array('code' => 'IDPSJ', 'name' => 'Poso, Sulawesi'),
            array('code' => 'IDPOT', 'name' => 'Poto Tano'),
            array('code' => 'IDPRO', 'name' => 'Probolinggo, Java'),
            array('code' => 'IDPNT', 'name' => 'Prointal, Jv'),
            array('code' => 'IDPPS', 'name' => 'Pulangpisau'),
            array('code' => 'IDPBJ', 'name' => 'Pulau Bunyu'),
            array('code' => 'IDPUT', 'name' => 'Pulau Laut'),
            array('code' => 'IDPPJ', 'name' => 'Pulau Panjang'),
            array('code' => 'IDPSS', 'name' => 'Pulau Sambu, Riau'),
            array('code' => 'IDPUR', 'name' => 'Purwakarta'),
            array('code' => 'IDPWL', 'name' => 'Purwokerto'),
            array('code' => 'IDPSU', 'name' => 'Putussibau'),
            array('code' => 'IDRAQ', 'name' => 'Raha'),
            array('code' => 'IDRNI', 'name' => 'Ranai'),
            array('code' => 'IDRSK', 'name' => 'Ransiki'),
            array('code' => 'IDREM', 'name' => 'Rembang'),
            array('code' => 'IDRGT', 'name' => 'Rengat, Sumatra'),
            array('code' => 'IDREO', 'name' => 'Reo'),
            array('code' => 'IDRKI', 'name' => 'Rokot'),
            array('code' => 'IDRTI', 'name' => 'Roti'),
            array('code' => 'IDRUN', 'name' => 'Rungkut'),
            array('code' => 'IDRTG', 'name' => 'Ruteng, Flores'),
            array('code' => 'IDSBG', 'name' => 'Sabang, Sumatra'),
            array('code' => 'IDSAD', 'name' => 'Sadau, Borneo'),
            array('code' => 'IDSTG', 'name' => 'Salatiga Semarang'),
            array('code' => 'IDSWT', 'name' => 'Salawati Terminal'),
            array('code' => 'IDSRI', 'name' => 'Samarinda, Kalimantan'),
            array('code' => 'IDSBS', 'name' => 'Sambas, Kalimantan'),
            array('code' => 'IDSMQ', 'name' => 'Sampit, Kalimantan'),
            array('code' => 'IDSQN', 'name' => 'Sanana'),
            array('code' => 'IDSAN', 'name' => 'Sanang, Celebes'),
            array('code' => 'IDSGQ', 'name' => 'Sanggata'),
            array('code' => 'IDSGU', 'name' => 'Sanggau'),
            array('code' => 'IDSAE', 'name' => 'Sangir'),
            array('code' => 'IDSKI', 'name' => 'Sangkulirang, Kalimantan'),
            array('code' => 'IDSAT', 'name' => 'Santan Terminal, Kl'),
            array('code' => 'IDZRM', 'name' => 'Sarmi'),
            array('code' => 'IDSAS', 'name' => 'Sasayap'),
            array('code' => 'IDSTU', 'name' => 'Satui'),
            array('code' => 'IDSXK', 'name' => 'Saumlaki'),
            array('code' => 'IDISO', 'name' => 'Sawahlunto'),
            array('code' => 'IDSAU', 'name' => 'Sawu'),
            array('code' => 'IDSEB', 'name' => 'Sebangan Bay, Kalimantan'),

            array('code' => 'IDSEG', 'name' => 'Segama, Borneo'),
            array('code' => 'IDSKP', 'name' => 'Sekupang'),
            array('code' => 'IDSPA', 'name' => 'Selat Pandjang, Sumatra'),
            array('code' => 'IDSMB', 'name' => 'Semangka Bay, St'),
            array('code' => 'IDTES', 'name' => 'Semarang'),
            array('code' => 'IDSRG', 'name' => 'Semarang, Java'),
            array('code' => 'IDSEH', 'name' => 'Senggeh'),
            array('code' => 'IDZEG', 'name' => 'Senggo'),
            array('code' => 'IDSZH', 'name' => 'Senipah'),
            array('code' => 'IDSPH', 'name' => 'Senipah Terminal'),
            array('code' => 'IDSER', 'name' => 'Serang'),
            array('code' => 'IDZRI', 'name' => 'Serui, Irian Jaya'),
            array('code' => 'IDSVP', 'name' => 'Sevivara Point'),
            array('code' => 'IDSSI', 'name' => 'Siak Sri Indrapura'),
            array('code' => 'IDSIA', 'name' => 'Siak Yechil, Riau'),
            array('code' => 'IDSIW', 'name' => 'Sibisa'),
            array('code' => 'IDSLG', 'name' => 'Sibolga, Sumatra'),
            array('code' => 'IDSID', 'name' => 'Sidangoli'),
            array('code' => 'IDSDJ', 'name' => 'Sidoarjo'),
            array('code' => 'IDSNG', 'name' => 'Sinabang'),
            array('code' => 'IDNKD', 'name' => 'Sinak'),
            array('code' => 'IDSKW', 'name' => 'Singkawang, Kalimantan'),
            array('code' => 'IDSIQ', 'name' => 'Singkep Isl Apt'),
            array('code' => 'IDSQG', 'name' => 'Sintang'),
            array('code' => 'IDRKO', 'name' => 'Sipora'),
            array('code' => 'IDCGK', 'name' => 'Soekarno-Hatta Apt/Jakarta'),
            array('code' => 'IDSKK', 'name' => 'Soengei Kolak'),
            array('code' => 'IDSOC', 'name' => 'Solo City'),
            array('code' => 'IDSQR', 'name' => 'Soroako'),
            array('code' => 'IDSOQ', 'name' => 'Sorong'),
            array('code' => 'IDZKL', 'name' => 'Steenkool'),
            array('code' => 'IDUAI', 'name' => 'Suai'),
            array('code' => 'IDSUA', 'name' => 'Suaran'),
            array('code' => 'IDSBM', 'name' => 'Subaim'),
            array('code' => 'IDSWQ', 'name' => 'Sumbawa'),
            array('code' => 'IDSUM', 'name' => 'Sumenep'),
            array('code' => 'IDSUP', 'name' => 'Sumenep, Madura'),
            array('code' => 'IDSUG', 'name' => 'Sungai Gerong, Sumatra'),
            array('code' => 'IDSUQ', 'name' => 'Sungai Guntung, Sumatra'),
            array('code' => 'IDSEQ', 'name' => 'Sungai Pakning, Sumatra'),
            array('code' => 'IDSUN', 'name' => 'Sunut'),
            array('code' => 'IDSUB', 'name' => 'Surabaya'),
            array('code' => 'IDSKT', 'name' => 'Surakarta'),
            array('code' => 'IDSUS', 'name' => 'Susoh, Sumatra'),
            array('code' => 'IDSSO', 'name' => 'Susu'),
            array('code' => 'IDTAB', 'name' => 'Taboneo'),
            array('code' => 'IDTAX', 'name' => 'Taliabu Island Apt, Moluccas'),
            array('code' => 'IDTMC', 'name' => 'Tambolaka'),
            array('code' => 'IDTTR', 'name' => 'Tana Toraja'),
            array('code' => 'IDTNB', 'name' => 'Tanah Grogot'),
            array('code' => 'IDTAL', 'name' => 'Tanah Laut'),
            array('code' => 'IDTMH', 'name' => 'Tanahmerah, Kalimantan'),
            array('code' => 'IDPDJ', 'name' => 'Tandjang'),
            array('code' => 'IDTBT', 'name' => 'Tandjung Batu, Riau'),
            array('code' => 'IDTRG', 'name' => 'Tangerang Tangerang'),
            array('code' => 'IDTJB', 'name' => 'Tanjung Balai'),
            array('code' => 'IDTBU', 'name' => 'Tanjung Buli'),
            array('code' => 'IDTME', 'name' => 'Tanjung Merangas'),
            array('code' => 'IDTJQ', 'name' => 'Tanjung Pandan'),
            array('code' => 'IDTPN', 'name' => 'Tanjung Pemancingan'),
            array('code' => 'IDTNJ', 'name' => 'Tanjung Pinang, Riau'),
            array('code' => 'IDTPP', 'name' => 'Tanjung Priok'),
            array('code' => 'IDTSX', 'name' => 'Tanjung Santan'),
            array('code' => 'IDTSE', 'name' => 'Tanjung Sekong, Jv'),
            array('code' => 'IDTJS', 'name' => 'Tanjung Selor'),
            array('code' => 'IDITN', 'name' => 'Tanjung Uban'),
            array('code' => 'IDTJG', 'name' => 'Tanjung Warukin'),
            array('code' => 'IDTJP', 'name' => 'Tanjungperak'),
            array('code' => 'IDTAN', 'name' => 'Tanjunguban'),
            array('code' => 'IDTPK', 'name' => 'Tapaktuan, Sumatra'),
            array('code' => 'IDTRH', 'name' => 'Tarahan'),
            array('code' => 'IDTRK', 'name' => 'Tarakan, Kalimantan'),
            array('code' => 'IDTAR', 'name' => 'Tarjun'),
            array('code' => 'IDTSY', 'name' => 'Tasikmalaya'),
            array('code' => 'IDTTI', 'name' => 'Tebingtinggi'),
            array('code' => 'IDTEG', 'name' => 'Tegal, Java'),
            array('code' => 'IDTKA', 'name' => 'Telok Ayer, Kalimantan'),
            array('code' => 'IDTMO', 'name' => 'Telok Melano'),
            array('code' => 'IDTBG', 'name' => 'Teluk Betung, Sumatra'),
            array('code' => 'IDTBR', 'name' => 'Telukbayur'),
            array('code' => 'IDTIM', 'name' => 'Tembagapura'),
            array('code' => 'IDTXM', 'name' => 'Teminabuan'),
            array('code' => 'IDTER', 'name' => 'Terempa'),
            array('code' => 'IDTTE', 'name' => 'Ternate, Halmahera'),
            array('code' => 'IDTMK', 'name' => 'Timika'),
            array('code' => 'IDTMY', 'name' => 'Tiom'),
            array('code' => 'IDTBO', 'name' => 'Tobelo'),
            array('code' => 'IDTLI', 'name' => 'Tolitoli'),
            array('code' => 'IDTUA', 'name' => 'Tual'),
            array('code' => 'IDTBN', 'name' => 'Tuban, Jv'),
            array('code' => 'IDTBM', 'name' => 'Tumbang Samba'),
            array('code' => 'IDUBR', 'name' => 'Ubrub'),
            array('code' => 'IDUPG', 'name' => 'Ujung Pandang, Sulawesi'),
            array('code' => 'IDVIQ', 'name' => 'Viqueque'),
            array('code' => 'IDWET', 'name' => 'Wagethe'),
            array('code' => 'IDWBA', 'name' => 'Wahai'),
            array('code' => 'IDWGP', 'name' => 'Waingapu, Sumba'),
            array('code' => 'IDWAI', 'name' => 'Wainibe'),
            array('code' => 'IDWMX', 'name' => 'Wamena'),
            array('code' => 'IDWSS', 'name' => 'Wamsasi'),
            array('code' => 'IDWAN', 'name' => 'Wanam'),
            array('code' => 'IDWAR', 'name' => 'Waris'),
            array('code' => 'IDWSR', 'name' => 'Wasior'),
            array('code' => 'IDWED', 'name' => 'Weda'),
            array('code' => 'IDWON', 'name' => 'Wonosari'),
            array('code' => 'IDJOG', 'name' => 'Yogyakarta'),
            array('code' => 'IDRUF', 'name' => 'Yuruf'),
            array('code' => 'IDUGU', 'name' => 'Zugapa'),

		);
        
    }
}
